AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - tmp/**/*
  - spec/fixtures/*

Layout/ArgumentAlignment:
  # Disable, till rubocop supports combination of styles.
  # Use one of this styles where appropriate, keep it clean, compact and readable.
  Enabled: false
  # EnforcedStyle:
  # - with_first_parameter
  # - with_fixed_indentation
Layout/ClosingParenthesisIndentation: {Enabled: false}
Layout/DotPosition: {EnforcedStyle: trailing}
Layout/EmptyLineAfterGuardClause: {Enabled: false}
Layout/FirstParameterIndentation: {EnforcedStyle: consistent}
Layout/MultilineOperationIndentation: {EnforcedStyle: indented}
Layout/SpaceInsideHashLiteralBraces: {EnforcedStyle: no_space}
Layout/LineLength: {Max: 100}

Metrics/AbcSize: {Max: 21}
Metrics/BlockLength: {Exclude: [spec/**/*]}
Metrics/MethodLength: {Max: 30}
Metrics/CyclomaticComplexity: {Max: 8}

Naming/PredicateName: {Enabled: false}

Style/Alias: {Enabled: false}
Style/AndOr: {EnforcedStyle: conditionals}
Style/Documentation: {Enabled: false}
Style/IfUnlessModifier: {Enabled: false}
Style/ModuleFunction: {Enabled: false}
Style/NestedParenthesizedCalls: {Enabled: false}
Style/SignalException: {EnforcedStyle: only_raise}
Style/TrailingCommaInArguments: {Enabled: false}
Style/TrailingCommaInArrayLiteral: {EnforcedStyleForMultiline: comma}
Style/TrailingCommaInHashLiteral: {EnforcedStyleForMultiline: comma}
